### ISSUE TITLE
What dose " closest_pt_tracking.launch " means ? 

### ISSUE THREAD

**Issue by howardjchen** [kuka-isir/kinects_human_tracking#1]
Hi Jimmy : 
   I'm Howard. Recently I found this awesome repository which utilize kinects to track humans.
Furthermore, I saw the TODO in README.md where you wrote about adopting particle filter for tracking point cloud. I think maybe I could help a little bit in this part. Therefore, I tried to get well known about your package and I got some questions about "current-settings" branch.
 1.  What dose the launch file "closest_pt_tracking.launch" do ?  Which you didn't mention in README.md
 2.  What's the different between kinects_human_tracking.launch and closest_pt_tracking.launch ? 

Many thanks at first.
Thank you for consideration for any inconvenience caused.
Howard.

**Comment by JimmyDaSilva** [comment]
Hello Howard @s880367 .
I am glad you find this package interesting. Sorry for the mess. I wasn't expecting anyone to use this YET.

First let me clarify things here. The package is designed to be used for tracking clusters of objects/humans moving around a robot.

The README is outdated ... There is no difference between the two launch, it has just been renamed. By the way kinects_human_tracking.launch does not exist anymore in both branches.

"closest_pt_tracking" basically means that I am tracking only the closest cluster to the robot.

I am going to make huge changes to this package in the next month. 

Let me know if you have more questions,
Jimmy

**Comment by howardjchen** [comment]
Hi Jimmy: 
    Thanks for your reply. I'm looking forward to see the change of this packages. 
Howard.
