### ISSUE TITLE
[ERROR] datatype does not match

### ISSUE THREAD

**Issue by lyh458** [kuka-isir/kinects_human_tracking#3]
Hi,
Thanks for your awesome works! When I launch [kinect_merge.launch](https://github.com/kuka-isir/kinects_human_tracking/blob/master/launch/kinect_merge.launch), an error about datatype mismatching occurred in the terminator window of [kinect_img_bg_sub.launch](https://github.com/kuka-isir/kinects_human_tracking/blob/master/launch/kinect_img_bg_sub.launch), details as follows:

```
[ERROR] [1608344104.584879506]: Client [/kinects_merge] wants topic /kinect2/qhd/background_sub to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743]. Dropping connection.
```

I noticed that the topic **/background_sub** (which is the input topic of kinect_merge.launch) is defined as ``sensor_msgs::Image``(depth image?) in node [kinect_img_bg_sub](https://github.com/kuka-isir/kinects_human_tracking/blob/master/src/kinect_img_bg_sub.cpp#L20), however, the topic type of node [kinects_merge](https://github.com/kuka-isir/kinects_human_tracking/blob/db2a47a8066a3786443e6332eba622e95708bed9/src/merge_kinects_pc.cpp#L44) wants to subscribe is **PCMsg** (pointcloud2?). Is that true? If so, how can you roslaunch it successfully?
ps: I only use one kinect.

**Comment by lyh458** [comment]
And I changed the topic **/background_sub** to **/downsampled_filtered_points** in [kinect_merge.launch](https://github.com/kuka-isir/kinects_human_tracking/blob/master/launch/kinect_merge.launch#L2), I think which is more reasonable and roslaunch it succeIssfully, but I am not sure it's right or not.

**Comment by JimmyDaSilva** [comment]
Hi @lyh458,
This is an old work, and I don't have access to a Kinect right to test the current state of the master branch with the latest version of ROS.

> [ERROR] [1608344104.584879506]: Client [/kinects_merge] wants topic /kinect2/qhd/background_sub to have datatype/md5sum [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181], but our version has [sensor_msgs/Image/060021388200f6f0f447d0fcd9c64743]. Dropping connection.

Anyway, this issue states clearly that you doing something wrong with the nodes. 
This error means that when launching kinect_img_bg_sub.launch , the "backgroung_sub" topic is an image.
Then you call kinect_merge and the node seeks for a Pointcloud type on this same topic.

Between "merge" and "kinect_img_sub" you need to call the create_poincloud node as said in the README.
Even with only one kinect.
For the 1 kinect case, here is the list of roslaunch to start:

```
roslaunch lwr_description lwr_test.launch (or another robot)
roslaunch kinects_human_tracking kinect1.launch
roslaunch kinects_human_tracking kinect1_extrinsics.launch
roslaunch realtime_urdf_filter filter.launch kinect_name:=kinect1
roslaunch kinects_human_tracking kinect_img_bg_store.launch kinect_name:=kinect1
roslaunch kinects_human_tracking kinect_img_bg_sub.launch kinect_name:=kinect1
roslaunch realtime_urdf_filter create_pc.launch kinect_name:=kinect1
roslaunch kinects_human_tracking kinect_merge.launch topic_name1:=/kinect1/depth_registered/downsampled_filtered_points 
roslaunch kinects_human_tracking closest_pt_tracking.launch
```

**Comment by lyh458** [comment]
It is my mistake that used the default value **/background_sub** instead of the arg ``topic_name1:=/kinect1/depth_registered/downsampled_filtered_points``, sorry for my overlooking.
BTW, I think its not a good idea to set **/background_sub** as the default value, which will result in the datatype mismatching error.

**Comment by JimmyDaSilva** [comment]
Glad it works for you.
I agree, I should change the default topic 

Le 23 déc. 2020 à 08:46, à 08:46, Yihui Li <notifications@github.com> a écrit:

**Comment by lyh458** [comment]
It's an awesome work that you showed in the video [Human/robot safe cooperation - RVIZ](https://www.youtube.com/watch?v=kc1JB106Xrc), is that an experiment of one of your publications or blogs? or codes?

**Comment by vpadois** [comment]
Hi Yihui Li,

The use of this code is for example illustrated in this paper which you may want to cite in your own work :
https://hal.archives-ouvertes.fr/hal-01398790/document
https://hal.archives-ouvertes.fr/hal-01614508v2/document
https://hal.archives-ouvertes.fr/hal-01883995/document
https://hal.archives-ouvertes.fr/hal-02434905v3/document

Thanks for your feedback on this work.

Best regards
Vincent Padois

**Comment by lyh458** [comment]
Thank you @vpadois !
